name: Build libssh2 Libraries (Android)

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
    steps:
    - uses: actions/checkout@v4.1.7
      with:
        repository: 'libssh2/libssh2'
        path: 'libssh2'
        ref: 'libssh2-1.11.0'
        submodules: true

    - name: Install dependencies on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Install Android SDK Command-Line Tools
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O android-sdk-tools.zip
        unzip android-sdk-tools.zip -d tools
        mkdir $HOME/android-sdk/
        mkdir $HOME/android-sdk/cmdline-tools/
        mkdir $HOME/android-sdk/cmdline-tools/latest/
        mv ./tools/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/
        chmod +x $HOME/android-sdk/cmdline-tools/latest/bin/*
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        
    - name: Accept Android SDK Licenses
      run: |
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses


    - name: Install Specific Android NDK Version 26.3.11579264
      run: |
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --install "ndk;26.3.11579264"      
        echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/26.3.11579264" >> $GITHUB_ENV
        echo "PATH=$PATH:$ANDROID_HOME/ndk/26.3.11579264" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
         cd libssh2
         git clone https://github.com/microsoft/vcpkg.git
         ./vcpkg/bootstrap-vcpkg.sh
         ./vcpkg/vcpkg install openssl:x64-android zlib:x64-android
         ./vcpkg/vcpkg install openssl:arm64-android zlib:arm64-android

    - name: Build libssh2 for arm64-v8a
      run: |
          cd libssh2
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_SYSTEM_NAME=Android \
                -DCMAKE_ANDROID_NDK=$ANDROID_NDK_HOME \
                -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
                -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang \
                -DCMAKE_ANDROID_STL_TYPE=c++_shared \
                -DCMAKE_ANDROID_API=21 \
                -DCMAKE_TOOLCHAIN_FILE="./vcpkg/scripts/buildsystems/vcpkg.cmake" \
                -S ./ \
                -B ./build/arm64-v8a
          cmake --build ./build/arm64-v8a --config Release

    - name: Build libssh2 for x86_64
      run: |
          cd libssh2
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_SYSTEM_NAME=Android \
                -DCMAKE_ANDROID_NDK=$ANDROID_NDK_HOME \
                -DCMAKE_ANDROID_ARCH_ABI=x86_64 \
                -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang \
                -DCMAKE_ANDROID_STL_TYPE=c++_shared \
                -DCMAKE_ANDROID_API=21 \
                -DCMAKE_TOOLCHAIN_FILE="./vcpkg/scripts/buildsystems/vcpkg.cmake" \
                -S ./ \
                -B ./build/x86_64
          cmake --build ./build/x86_64 --config Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.3.4
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}-artifacts 
        path: |
          libssh2/build/arm64-v8a/src/*.so
          libssh2/build/x86_64/src/*.so
        if-no-files-found: ignore # 'warn' or 'ignore' or 'error'
